# Generated by Django 3.0.3 on 2021-10-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'Normal User', 'verbose_name_plural': 'Normal Users'},
        ),
    ]
